using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GlobalERCDY : MonoBehaviour
{
    [Header("Inspector References")]
    public GameObject fakeButton;
    public GameObject fakeText;
    public GameObject realButton;
    public GameObject realText;
    public GameObject sellTen;

    [HideInInspector] public int currentCash;
    public static int ERCDYvalue = 50;
    private bool thresholdReached = false;
    private bool gateBool = true;

    public static int autoCookiePerSecond; //the int which represents how many cookies per second are being autogenerated. 

    void Update()
    {
        currentCash = GlobalCash.cashCount;

        if (currentCash >= (ERCDYvalue * 0.5) && gateBool == true)
        {
            thresholdReached = true;
            gateBool = false;
            sellTen.SetActive(true);
            fakeButton.SetActive(true);
        }

        if (thresholdReached == true)
        {
            fakeText.GetComponent<Text>().text = "Enhance Regular Cookie Dividend Yield - $" + ERCDYvalue;
            realText.GetComponent<Text>().text = "Enhance Regular Cookie Dividend Yield - $" + ERCDYvalue;

            if (currentCash >= ERCDYvalue)
            {
                fakeButton.SetActive(false);
                realButton.SetActive(true);
            }
            else
            {
                fakeButton.SetActive(true);
                realButton.SetActive(false);
            }
        }
    }
}
